// <auto-generated />
namespace Final_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class enrollunassign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enrollunassign));
        
        string IMigrationMetadata.Id
        {
            get { return "201809271613149_enrollunassign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
