// <auto-generated />
namespace Final_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class enrrrrolll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enrrrrolll));
        
        string IMigrationMetadata.Id
        {
            get { return "201809271955582_enrrrrolll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
